#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
NVIM_INSTALL_DIR="$XDG_CONFIG_HOME/nvim"

install() {
    case $(__os) in
      macos) __nan_has nvim || brew install neovim ;;
    esac
    
    # if [[ ! topic-enabled-p dev/node ]]; then
    #   __nan_warn "Node not present on system."
    # fi
    # if [[ ! topic-enabled-p dev/python ]]; then
    #   __nan_warn "Python not enabled on system."
    # fi
    __nan_ok "Installed plug.vim."
    __ensure_repo nnothstine/nvim $XDG_CONFIG_HOME/nvim
    nvim +PlugInstall +qa
}

link() {
    # __nan_link $NVIM_INSTALL_DIR $XDG_CONFIG_HOME/vim
}

clean() {
    rm -rfv $NVIM_INSTALL_DIR
    rm -rfv $XDG_CONFIG_HOME/vim
}

init "$@"
