#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
NVIM_INSTALL_DIR="$XDG_CONFIG_HOME/nvim"

install() {
    case $(__os) in
    macos) __nan_has nvim || brew install neovim ;;
    esac

    # curl -fLo $XDG_DATA_HOME/site/autoload/plug.vim --create-dirs \
    #     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    __nan_ok "Installed plug.vim."
    __ensure_repo nnothstine/nvim $XDG_CONFIG_HOME/nvim
}

link() {
    # __nan_link $NVIM_INSTALL_DIR $XDG_CONFIG_HOME/vim
}

clean() {
    rm -rfv $NVIM_INSTALL_DIR
    rm -rfv $XDG_CONFIG_HOME/vim
}

init "$@"
