#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(__os) in
    macos*) brew install goenv ;;
  esac
}

update() {
  case $(__os) in
    macos*) brew update ;;
  esac
}

# link() {}

clean() {
  [[ $(__os) == "macos" ]] && brew uninstall goenv
}

init "$@"