#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
    case $(__os) in
    macos*) brew install tmux ;;
    esac

    __ensure_repo tmux-plugins/tpm "${DOTFILES}/shell/tmux/plugins/tpm" && \
        "$DOTFILES/shell/tmux/plugins/tpm/bin/install_plugins"
}

link() {
}

update() {
}

clean() {
    [[ $(__os) == macos ]] && {
        brew uninstall tmux
    }
}

init "$@"
