#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(__os) in
    macos) brew install rbenv ;;
  esac
}

update() {
  # TODO
}

link() {
  # TODO
}

clean() { 
  rm -rfv $RBENV_ROOT
  case $(__os) in
    macos*) brew uninstall rbenv ;;
  esac
}

init "$@"
