#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
    case $(__os) in
        macos) brew install pyenv pipenv
    esac
    # TODO: Is there a reasonable way of making this more generic?
    pyenv install 3.8.1
    pyenv install 2.7.17
}

update() {
    # TODO
}

link() {
    # TODO
}

clean() {
    rm -rfv $PYENV_ROOT
}

init "$@"