#!/usr/bin/env zsh

__add_app_to_dock() {
  # adds an application to macOS Dock
  # usage: add_app_to_dock "Application Name" 
  # example add_app_to_dock "Terminal"

  app_name="${1}"
  launchservices_path="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"
  app_path=$(${launchservices_path} -dump | grep -o "/.*${app_name}.app" | grep -v -E "Backups|Caches|TimeMachine|Temporary|/Volumes/${app_name}" | uniq | sort | head -n1)
  if open -Ra "${app_path}"; then
      echo "$app_path added to the Dock."
      defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>${app_path}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
  else
      echo "ERROR: $1 not found." 1>&2
  fi
}

__add_spacer_to_dock() {
  # adds an empty space to macOS Dock
  defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}'
}

__clear_dock() {
  # removes all persistent icons from macOS Dock
  defaults write com.apple.dock persistent-apps -array
}

__reset_dock() {
  # reset macOS Dock to default settings
  defaults write com.apple.dock; killall Dock
}

# WARNING: permanently clears existing dock
__clear_dock

__add_app_to_dock "System Preferences"
__add_app_to_dock "Activity Monitor"
__add_app_to_dock "Console"
__add_app_to_dock "Terminal"
__add_spacer_to_dock
__add_app_to_dock "Safari"
__add_app_to_dock "Mail"
__add_app_to_dock "Calendar"
__add_app_to_dock "Music"
__add_app_to_dock "Books"
__add_app_to_dock "App Store"
__add_spacer_to_dock

killall Dock