#!/usr/bin/env zsh

__add_app_to_dock() {
    app_name="${1}"
    app_path=""

    # places to look for an application
    declare -a system_paths=(
    "/System/Applications"
    "/System/Applications/Utilities"
    "/System/Library/CoreServices"
    "/Applications"
    "$HOME/Applications"
    );

    # check the paths for the app
    for spath in "${system_paths[@]}"; do
        app=$(ls "${spath}" | grep -o "${app_name}.app" | uniq | sort | head -n1)
        if [[ -n "${app}" ]]; then
            app_path="${spath}/${app}"
        fi
    done

    if open -Ra "${app_path}"; then
        echo "Dock: $app_path added to the Dock."

        defaults write com.apple.dock persistent-apps -array-add "<dict>
            <key>tile-data</key>
            <dict>
                <key>file-data</key>
                <dict>
                    <key>_CFURLString</key>
                    <string>${app_path}</string>
                    <key>_CFURLStringType</key>
                    <integer>0</integer>
                </dict>
            </dict>
        </dict>"
    else
        echo "ERROR: Application $1 not found." 1>&2
    fi
}

__add_spacer_to_dock() {
  # adds an empty space to macOS Dock
  defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}'
}

__clear_dock() {
  # removes all persistent icons from macOS Dock
  defaults write com.apple.dock persistent-apps -array
}

__reset_dock() {
  # reset macOS Dock to default settings
  defaults write com.apple.dock; killall Dock
}

# WARNING: permanently clears existing dock
__clear_dock

__add_app_to_dock "Finder"
__add_app_to_dock "Launchpad"
__add_app_to_dock "Safari"
# __add_app_to_dock "Mail"
__add_app_to_dock "Messages"
__add_app_to_dock "Mail"
__add_app_to_dock "Photos"
__add_app_to_dock "Reminders"
__add_app_to_dock "Notes"
__add_app_to_dock "Music"
__add_app_to_dock "App Store"
__add_app_to_dock "Shadow"
__add_app_to_dock "Steam"
__add_app_to_dock "System Preferences"

killall Dock
