#!/usr/bin/env zsh

source "${0:A:h}/../../deploy"

install() {
    if ! __nan_has brew; then
        # TODO: What happens to this when /usr/bin/ruby goes away?
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
    touch ~/.hushlogin
    brew install wget
    cp -a /System/Applications/Utilities/Terminal.app/Contents/Resources/Fonts/SFMono-* /Library/Fonts
    mkdir ~/{Projects,Sandbox}
}

update() {
    if __nan_prefer brew; then
        brew update && brew upgrade && brew cleanup
    else
        __nan_err "homebrew not detected"
    fi
}

link() {
    #__nan_link .hushlogin ~/.hushlogin
}

clean() { rm -fv ~/.hushlogin }

init "$@"
