#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(__os) in
  macos)
    brew tap d12frosted/emacs-plus
    brew install emacs-plus
    ln -s $(brew --prefix)/Cellar/emacs-plus/*/Emacs.app/ /Applications/
    ;;
  arch) yay --needed --noconfirm -S make emacs ;;
  esac

  __ensure_repo hlissner/doom-emacs $XDG_CONFIG_HOME/emacs
  __ensure_repo nnothstine/emacs-config $XDG_CONFIG_HOME/doom
  $XDG_CONFIG_HOME/emacs/bin/doom install --doomdir $XDG_CONFIG_HOME/doom
}

update() {
  cd $XDG_CONFIG_HOME/emacs && YES=1 make update
  $XDG_CONFIG_HOME/bin/doom upgrade
}

link() {
  # ln -s $(brew --prefix)/Cellar/emacs-plus/*/Emacs.app/ /Applications/
}

clean() {
  rm -rfv ~/.emacs.d
  case $(__os) in
  macos) brew untap d12frosted/emacs-plus ;;
  esac
}

init "$@"
