#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source .zshenv

install() {
    case $(__os) in
        macos) brew install sk ;;
    esac

    [[ $SHELL == */zsh ]] || chsh -s $(which zsh) $(whoami)
    # TODO: Does this go somewhere else?
    mkdir -p $ZSH_CACHE
}

link() {
    __nan_link .zsh* $ZDOTDIR/
    __nan_link functions $ZDOTDIR/
    [[ $(__os) == macos ]] && __nan_link .zshenv ~/.zshenv
}

update() {
    # [[ -e $ZINITDIR/zinit.zsh ]] && {

    # }
    zinit update --all
    zinit self-update
}

clean() {
    rm -rfv $ZDOTDIR
    [[ $(__os) == macos ]] && rm -f ~/.zshenv
}

init "$@"