#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source .zshenv

install() {
    case $(__os) in
        macos) brew install fzf ;;
    esac

    [[ $SHELL == */zsh ]] || chsh -s $(which zsh) $(whoami)
}

link() {
    __nan_link .zsh* $ZDOTDIR/
    [[ $(__os) == macos ]] && __nan_link .zshenv ~/.zshenv
}

init "$@"