#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
    case $(__os) in
    macos) brew install --cask iterm2 ;;
    esac
}

# update() {
# }

link() {
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DOTFILES/misc/iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

clean() {
    rm -rfv ~/.emacs.d
    case $(__os) in
    macos) brew uninstall --cask iterm2 ;;
    esac
}

init "$@"
