#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  __ensure_repo nodenv/nodenv $NODENV_ROOT
  __ensure_repo nodenv/node-build $NODENV_ROOT/plugins/node-build
  local node_version=$(nodenv install --list | grep -v "^[^0-9]" | grep -v -e "-" -e "dev" -e "next" -e "rc" | tail -1)
  nodenv install $node_version && nodenv global $node_version
}

update() {
  if [[ -n $NODENV_ROOT ]]; then
    cd $NODENV_ROOT && git pull
    for ver in $NODENV_ROOT/plugins/*(/); do
      cd $ver && git pull
    done
  fi
}

# link() {}

clean() {
  rm -rf $NODENV_ROOT
}

init "$@"
