#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(__os) in
    macos) brew install nodenv ;;
  esac
  __ensure_repo nodenv/nodenv $NODENV_ROOT
  __ensure_repo nodenv/node-build $NODENV_ROOT/plugins/node-build
  __ensure_repo momo-lab/xxenv-latest "$NODENV_ROOT/plugins/xxenv-latest"
  nodenv latest install
  nodenv latest global
}

update() {
  if [[ -n $NODENV_ROOT ]]; then
    cd $NODENV_ROOT && git pull
    for ver in $NODENV_ROOT/plugins/*(/); do
      cd $ver && git pull
    done
  fi
}

# link() {}

clean() {
  case $(__os) in
    macos) brew uninstall nodenv ;;
  esac
  rm -rf $NODENV_ROOT
}

init "$@"
